# Generated by Django 2.1.1 on 2018-10-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20181031_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
