# Generated by Django 2.1.1 on 2018-11-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='question',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
    ]
